# Generated by Django 5.2.1 on 2025-05-24 11:36

import django.utils.timezone
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=100, unique=True, verbose_name='display name')),
                ('text', models.TextField(verbose_name='text')),
                ('status', models.CharField(choices=[('pub', 'published'), ('drf', 'draft'), ('rjt', 'scheduled')], max_length=3, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'comment',
                'verbose_name_plural': 'comments',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='title')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='slug')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='blog images/', verbose_name='featured image')),
                ('main_content', tinymce.models.HTMLField(verbose_name='main content')),
                ('status', models.CharField(choices=[('pub', 'published'), ('SCD', 'scheduled'), ('drf', 'draft')], max_length=3, verbose_name='status')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('views', models.PositiveIntegerField(default=0, verbose_name='views')),
                ('is_featured', models.BooleanField(default=False, verbose_name='is featured')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'blog posts',
                'verbose_name_plural': 'post',
            },
        ),
    ]
