# Generated by Django 5.2.1 on 2025-05-24 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Categories',
            field=models.ManyToManyField(related_name='posts', to='categories.category', verbose_name='categories'),
        ),
    ]
